baseURL = "https://mawildoer.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Matt Wildoer's Website"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Hi! I'm Matt"
author = "Matt Wildoer"
fullPostContent = true
#copyright = "2020-2021"
description = "I love developing technology."
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = ["css/custom.css"]
# example ["js/custom.js"]
customJs = [] 
mainSections = ["about"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
contactFormAction = "https://formspree.io/f/mbjpnkzd"
# Google Site Verify
#googleSportfolioiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/matthew-wildoer-467a4992/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/mawildoer"


## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Portfolio"
  weight = 200
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"

## Taxonomies for Opengraph
[taxonomies]
  series = "series"
